apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: chargeops-nfs
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
parameters:
  archiveOnDelete: "true"
