apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: dev
  labels:
    app: booking-service
spec:
  type: ClusterIP
  selector:
    app: booking-service
  ports:
    - name: http
      port: 8004
      targetPort: http
