apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - network-policies.yaml
  - admin-service/deployment.yaml
  - admin-service/hpa.yaml
  - admin-service/service.yaml
  - auth-service/deployment.yaml
  - auth-service/hpa.yaml
  - auth-service/service.yaml
  - user-service/deployment.yaml
  - user-service/hpa.yaml
  - user-service/service.yaml
  - station-service/deployment.yaml
  - station-service/hpa.yaml
  - station-service/service.yaml
  - booking-service/deployment.yaml
  - booking-service/hpa.yaml
  - booking-service/service.yaml
  - payment-service/deployment.yaml
  - payment-service/hpa.yaml
  - payment-service/service.yaml
  - review-service/deployment.yaml
  - review-service/hpa.yaml
  - review-service/service.yaml
  - mongodb/deployment.yaml
  - mongodb/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
