sonar.projectKey=chargeops-auth-service
sonar.projectName=ChargeOps Auth Service
sonar.sources=.
sonar.exclusions=node_modules/**,coverage/**,**/*.test.js,**/*.spec.js
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.plugins.downloadOnlyRequired=true
