apiVersion: v1
kind: Service
metadata:
  name: auth-service-preview
  namespace: prod
spec:
  type: ClusterIP
  selector:
    app: auth-service
    role: preview
  ports:
    - name: http
      port: 3001
      targetPort: 3001
