apiVersion: v1
kind: Service
metadata:
  name: auth-service-active
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: auth-service
    role: active
  ports:
    - name: http
      port: 3001
      targetPort: 3001
