apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - storage.yaml
  - ../../base

patches:
  - path: frontend-service-patch.yaml
  - path: mongodb-deployment-patch.yaml

images:
  - name: chargeops-frontend
    newName: dhaniga/chargeops-frontend
    newTag: v1
  - name: chargeops-api-gateway
    newName: dhaniga/chargeops-api-gateway
    newTag: v1
  - name: chargeops-auth-service
    newName: dhaniga/auth-service
    newTag: v1
  - name: chargeops-user-service
    newName: dhaniga/user-service
    newTag: v1
  - name: chargeops-station-service
    newName: dhaniga/station-service
    newTag: v1
  - name: chargeops-booking-service
    newName: dhaniga/booking-service
    newTag: v1
  - name: chargeops-payment-service
    newName: dhaniga/payment-service
    newTag: v1
  - name: chargeops-review-service
    newName: dhaniga/review-service
    newTag: v1
  - name: chargeops-admin-service
    newName: dhaniga/admin-service
    newTag: v1
