apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dev-gateway-parameters.yaml
  - prod-gateway-parameters.yaml
  - dev-gateway.yaml
  - prod-gateway.yaml
  - dev-httproutes.yaml
  - prod-httproutes.yaml
