apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayParameters
metadata:
  name: chargeops-prod-gateway-params
  namespace: prod
spec:
  kube:
    service:
      type: NodePort
      extraLabels:
        app: kgateway-proxy
        gateway: chargeops
      externalTrafficPolicy: Local
    podTemplate:
      extraLabels:
        app: kgateway-proxy
        gateway: chargeops
