apiVersion: v1
kind: Service
metadata:
  name: admin-service-active
  namespace: prod
spec:
  type: ClusterIP
  selector:
    app: admin-service
    role: active
  ports:
    - name: http
      port: 3000
      targetPort: 3000
