apiVersion: v1
kind: Service
metadata:
  name: frontend-active
  namespace: prod
spec:
  type: LoadBalancer
  selector:
    app: frontend
    role: active
  ports:
    - name: http
      port: 80
      targetPort: 80
