param(
    [string]$OutputDir = (Join-Path $PSScriptRoot "..\split-output")
)

$ErrorActionPreference = "Stop"

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$manifestPath = Join-Path $repoRoot "repo-split.manifest.json"

if (-not (Test-Path $manifestPath)) {
    throw "Manifest not found: $manifestPath"
}

$manifest = Get-Content $manifestPath -Raw | ConvertFrom-Json
if ([System.IO.Path]::IsPathRooted($OutputDir)) {
    $resolvedOutputDir = [System.IO.Path]::GetFullPath($OutputDir)
} else {
    $resolvedOutputDir = [System.IO.Path]::GetFullPath((Join-Path $repoRoot $OutputDir))
}

if (Test-Path $resolvedOutputDir) {
    Remove-Item -LiteralPath $resolvedOutputDir -Recurse -Force
}

New-Item -ItemType Directory -Path $resolvedOutputDir | Out-Null

function Copy-Tree {
    param(
        [Parameter(Mandatory = $true)][string]$Source,
        [Parameter(Mandatory = $true)][string]$Destination
    )

    New-Item -ItemType Directory -Path $Destination -Force | Out-Null

    Get-ChildItem -LiteralPath $Source -Force | Where-Object {
        $_.Name -notin @(".git", "node_modules", "dist", "build", "coverage")
    } | ForEach-Object {
        $targetPath = Join-Path $Destination $_.Name
        if ($_.PSIsContainer) {
            Copy-Tree -Source $_.FullName -Destination $targetPath
        } else {
            Copy-Item -LiteralPath $_.FullName -Destination $targetPath -Force
        }
    }
}

function Write-RepoReadme {
    param(
        [Parameter(Mandatory = $true)][string]$RepoName,
        [Parameter(Mandatory = $true)][string]$RepoKind,
        [Parameter(Mandatory = $true)][string]$Destination,
        [string]$SourcePath,
        [Nullable[int]]$Port = $null
    )

    $content = @(
        "# $RepoName",
        "",
        "Generated from the ChargeOps monorepo to support a multi-repository microservices layout.",
        "",
        ("- Repo type: ``{0}``" -f $RepoKind),
        ("- Source path in monorepo: ``{0}``" -f $SourcePath)
    )

    if ($Port) {
        $content += ("- Default service port: ``{0}``" -f $Port)
    }

    $content += @(
        "",
        "## Local Start",
        "",
        'Run `npm install` and then `npm run start`.',
        "",
        "## Note",
        "",
        'This repository was generated by `scripts/prepare-microservice-repos.ps1` from the original `ChargeOps` monorepo.'
    )

    Set-Content -LiteralPath (Join-Path $Destination "README.md") -Value ($content -join "`r`n")
}

foreach ($repo in $manifest.repos) {
    $destination = Join-Path $resolvedOutputDir $repo.name
    New-Item -ItemType Directory -Path $destination -Force | Out-Null

    if ($repo.source) {
        $source = Join-Path $repoRoot $repo.source
        Copy-Tree -Source $source -Destination $destination
        Write-RepoReadme -RepoName $repo.name -RepoKind $repo.kind -Destination $destination -SourcePath $repo.source -Port $repo.port
    } elseif ($repo.sources) {
        foreach ($relativeSource in $repo.sources) {
            $source = Join-Path $repoRoot $relativeSource
            $leafName = Split-Path $relativeSource -Leaf
            if (Test-Path $source -PathType Container) {
                Copy-Tree -Source $source -Destination (Join-Path $destination $leafName)
            } else {
                Copy-Item -LiteralPath $source -Destination (Join-Path $destination $leafName) -Force
            }
        }
        Write-RepoReadme -RepoName $repo.name -RepoKind $repo.kind -Destination $destination -SourcePath ($repo.sources -join ", ")
    }

    Copy-Item -LiteralPath (Join-Path $repoRoot ".gitignore") -Destination (Join-Path $destination ".gitignore") -Force
    Set-Content -LiteralPath (Join-Path $destination "repo-origin.txt") -Value "Generated from ChargeOps on $(Get-Date -Format s)"
}

Write-Host "Generated split repositories in $resolvedOutputDir"
