apiVersion: v1
kind: Secret
metadata:
  name: chargeops-secrets
  namespace: dev
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: admin
  MONGO_ROOT_PASSWORD: password123
  JWT_SECRET: myjwtsecret123
  API_KEY: testkey
  INTERNAL_SERVICE_API_KEY: testkey
  STRIPE_SECRET_KEY: testkey
