apiVersion: v1
kind: Service
metadata:
  name: review-service
  namespace: prod
  labels:
    app: review-service
spec:
  type: ClusterIP
  selector:
    app: review-service
  ports:
    - name: http
      port: 8006
      targetPort: http
