# .github/workflows/ci-security.yml
name: CI Security Pipeline

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:

# -----------------------------
# 1. Checkout Code
# -----------------------------
  security-checks:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Source Code
      uses: actions/checkout@v4

# -----------------------------
# 2. Setup Node.js
# -----------------------------
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

# -----------------------------
# 3. Install Dependencies
# -----------------------------
    - name: Install Dependencies
      run: npm install

# -----------------------------
# 4. SCA Scan (Dependency Check)
# -----------------------------
    - name: Run npm audit
      run: npm audit --audit-level=high

# -----------------------------
# 5. SAST Scan (CodeQL)
# -----------------------------
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: javascript

    - name: Autobuild
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

# -----------------------------
# 6. SonarQube Scan
# -----------------------------
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v6
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

# -----------------------------
# 7. Docker Build
# -----------------------------
    - name: Build Docker Image
      run: docker build -t dhaniga/chargeops-app:${{ github.sha }} .

# -----------------------------
# 8. Trivy Container Scan
# -----------------------------
    - name: Run Trivy Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: dhaniga/chargeops-app:${{ github.sha }}
        format: table
        exit-code: 0
        ignore-unfixed: true
        severity: CRITICAL,HIGH

# -----------------------------
# 9. Success
# -----------------------------
    - name: Completed
      run: echo "CI Security Checks Passed Successfully"
